//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Service1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service1.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/search", ReplyAction="*")]
        Client.Service1.searchResponse search(Client.Service1.searchRequest request);
        
        // CODEGEN: Generating message contract since element name searchAgeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchAge", ReplyAction="*")]
        Client.Service1.searchAgeResponse searchAge(Client.Service1.searchAgeRequest request);
        
        // CODEGEN: Generating message contract since element name getAllPersonsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllPersons", ReplyAction="*")]
        Client.Service1.getAllPersonsResponse getAllPersons(Client.Service1.getAllPersonsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="search", Namespace="http://tempuri.org/", Order=0)]
        public Client.Service1.searchRequestBody Body;
        
        public searchRequest() {
        }
        
        public searchRequest(Client.Service1.searchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class searchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public searchRequestBody() {
        }
        
        public searchRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.Service1.searchResponseBody Body;
        
        public searchResponse() {
        }
        
        public searchResponse(Client.Service1.searchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class searchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.Service1.Person[] searchResult;
        
        public searchResponseBody() {
        }
        
        public searchResponseBody(Client.Service1.Person[] searchResult) {
            this.searchResult = searchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchAgeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchAge", Namespace="http://tempuri.org/", Order=0)]
        public Client.Service1.searchAgeRequestBody Body;
        
        public searchAgeRequest() {
        }
        
        public searchAgeRequest(Client.Service1.searchAgeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class searchAgeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int age;
        
        public searchAgeRequestBody() {
        }
        
        public searchAgeRequestBody(int age) {
            this.age = age;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchAgeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchAgeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.Service1.searchAgeResponseBody Body;
        
        public searchAgeResponse() {
        }
        
        public searchAgeResponse(Client.Service1.searchAgeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class searchAgeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.Service1.Person[] searchAgeResult;
        
        public searchAgeResponseBody() {
        }
        
        public searchAgeResponseBody(Client.Service1.Person[] searchAgeResult) {
            this.searchAgeResult = searchAgeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllPersonsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllPersons", Namespace="http://tempuri.org/", Order=0)]
        public Client.Service1.getAllPersonsRequestBody Body;
        
        public getAllPersonsRequest() {
        }
        
        public getAllPersonsRequest(Client.Service1.getAllPersonsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllPersonsRequestBody {
        
        public getAllPersonsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllPersonsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllPersonsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.Service1.getAllPersonsResponseBody Body;
        
        public getAllPersonsResponse() {
        }
        
        public getAllPersonsResponse(Client.Service1.getAllPersonsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllPersonsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.Service1.Person[] getAllPersonsResult;
        
        public getAllPersonsResponseBody() {
        }
        
        public getAllPersonsResponseBody(Client.Service1.Person[] getAllPersonsResult) {
            this.getAllPersonsResult = getAllPersonsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : Client.Service1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<Client.Service1.Service1Soap>, Client.Service1.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.Service1.searchResponse Client.Service1.Service1Soap.search(Client.Service1.searchRequest request) {
            return base.Channel.search(request);
        }
        
        public Client.Service1.Person[] search(string str) {
            Client.Service1.searchRequest inValue = new Client.Service1.searchRequest();
            inValue.Body = new Client.Service1.searchRequestBody();
            inValue.Body.str = str;
            Client.Service1.searchResponse retVal = ((Client.Service1.Service1Soap)(this)).search(inValue);
            return retVal.Body.searchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.Service1.searchAgeResponse Client.Service1.Service1Soap.searchAge(Client.Service1.searchAgeRequest request) {
            return base.Channel.searchAge(request);
        }
        
        public Client.Service1.Person[] searchAge(int age) {
            Client.Service1.searchAgeRequest inValue = new Client.Service1.searchAgeRequest();
            inValue.Body = new Client.Service1.searchAgeRequestBody();
            inValue.Body.age = age;
            Client.Service1.searchAgeResponse retVal = ((Client.Service1.Service1Soap)(this)).searchAge(inValue);
            return retVal.Body.searchAgeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.Service1.getAllPersonsResponse Client.Service1.Service1Soap.getAllPersons(Client.Service1.getAllPersonsRequest request) {
            return base.Channel.getAllPersons(request);
        }
        
        public Client.Service1.Person[] getAllPersons() {
            Client.Service1.getAllPersonsRequest inValue = new Client.Service1.getAllPersonsRequest();
            inValue.Body = new Client.Service1.getAllPersonsRequestBody();
            Client.Service1.getAllPersonsResponse retVal = ((Client.Service1.Service1Soap)(this)).getAllPersons(inValue);
            return retVal.Body.getAllPersonsResult;
        }
    }
}
